### ISSUE TITLE
Error to create chat

### ISSUE THREAD

**Issue by GheorgheMocanu** [Elliott-Chong/chatpdf-yt#10]
I have this problem, dont know actually how to solved, learning by your video.
if somebody can help me please?

<img width="1680" alt="Screenshot 2023-09-21 at 01 17 14" src="https://github.com/Elliott-Chong/chatpdf-yt/assets/101702271/e3e25850-27c5-4864-92de-9efaf5a4ce03">

this is my terminal:

 ⚠ ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx

./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
Module not found: Can't resolve 'aws-crt' in '/Users/goga/Documents/myProjects/chatpdf/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx
 ⚠ ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx

./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
Module not found: Can't resolve 'aws-crt' in '/Users/goga/Documents/myProjects/chatpdf/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx
 ⚠ ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx

./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
Module not found: Can't resolve 'aws-crt' in '/Users/goga/Documents/myProjects/chatpdf/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx
 ⚠ ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx

./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
Module not found: Can't resolve 'aws-crt' in '/Users/goga/Documents/myProjects/chatpdf/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/lib/s3.ts
./src/components/FileUpload.tsx

./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/goga/Documents/myProjects/chatpdf/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@pinecone-database/pinecone/dist/pinecone.js
./node_modules/@pinecone-database/pinecone/dist/index.js
./src/lib/pincecone.ts
./src/app/api/create-chat/route.ts
uploads/1695248226308the-weekend.pdf the weekend.pdf
downloading s3 into file system
loading pdf into memory/tmp/elliott1695248229781.pdf
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 2)
    at async loadS3IntoPinecone (webpack-internal:///(rsc)/./src/lib/pincecone.ts:41:21)
    at async POST (webpack-internal:///(rsc)/./src/app/api/create-chat/route.ts:31:9)
    at async /Users/goga/Documents/myProjects/chatpdf/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:1:66877
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 2)
    at async loadS3IntoPinecone (webpack-internal:///(rsc)/./src/lib/pincecone.ts:41:21)
    at async POST (webpack-internal:///(rsc)/./src/app/api/create-chat/route.ts:31:9)
    at async /Users/goga/Documents/myProjects/chatpdf/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:1:66877
TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 2)
    at async loadS3IntoPinecone (webpack-internal:///(rsc)/./src/lib/pincecone.ts:41:21)
    at async POST (webpack-internal:///(rsc)/./src/app/api/create-chat/route.ts:31:9)
    at async /Users/goga/Documents/myProjects/chatpdf/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:1:66877
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 3)
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 3)
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 4)
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 4)
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 1)
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 1)
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 0)
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 0)
error calling openai embeddings api TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 5)
error embedding document TypeError: Cannot read properties of undefined (reading '0')
    at getEmbeddings (webpack-internal:///(rsc)/./src/lib/embeddings.ts:18:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async embedDocument (webpack-internal:///(rsc)/./src/lib/pincecone.ts:52:28)
    at async Promise.all (index 5)

**Comment by AymanBoumait** [comment]
if you found a solution, let me know

**Comment by AymanBoumait** [comment]
@Elliott-Chong

**Comment by GheorgheMocanu** [comment]
What steps did I take?
At first I followed the video and learned how you showed me, but I got to this problem at 2:30:00.
I thought it was a problem on my part or maybe I didn't write something correctly in the code, then:
I downloaded the project from github
I replaced the keys in .env
But I get the same error

**Comment by AymanBoumait** [comment]
maybe the problem is because of pinecone

**Comment by GheorgheMocanu** [comment]
> maybe the problem is because of pinecone

for you its work ?

**Comment by AymanBoumait** [comment]
no I have the same issue as you

**Comment by huynextlevel** [comment]
Hi @AymanBoumait  and @GheorgheMocanu ,

The error coming 2 things:
1. Pinecone
2. Open AI API Token

In my case, because of my Open AI token. So I get the same error like you guys. The error coming from line 50 (image attached).

<img width="641" alt="Screenshot 2023-09-23 at 01 08 45" src="https://github.com/Elliott-Chong/chatpdf-yt/assets/73922436/18cd3ec7-82a4-4736-84ce-d6473e53c9f3">

**Comment by 0xalphaprime** [comment]
I'm having the same issue. getting held up ~2:30.

I started throwing a type error following the video on loadS3IntoPinecone() relating to `namespace`. In diagnosing I noticed changes made to the libraries imported from Pinecone for pinecone.ts. I've reviewed and tried to make necessary changes, but am now receiving the same errors described here.

**Comment by GheorgheMocanu** [comment]
> Hi @AymanBoumait and @GheorgheMocanu ,
> 
> The error coming 2 things:
> 
> 1. Pinecone: You need to create index `chatpf` on Pinecone dashboard
> 2. Open AI API Token
> 
> In my case, because of my Open AI token. I didn't setup payment methods on OpenAI, so my token is not available to use. So I get the same error like you guys. The error come from line `const vectors = await Promise.all(documents.flat().map(embedDocument))` (image attached).
> 
> <img alt="Screenshot 2023-09-23 at 01 08 45" width="641" src="https://user-images.githubusercontent.com/73922436/270019915-18cd3ec7-82a4-4736-84ce-d6473e53c9f3.png">

Hmmmm, I tried to follow the steps you mentioned.

1. 
![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/101702271/99d3e82c-bdd1-4100-8895-767c5cbdca79)

<img width="1680" alt="Screenshot 2023-09-24 at 15 56 59" src="https://github.com/Elliott-Chong/chatpdf-yt/assets/101702271/6663efed-570a-432d-a9d6-0cd207124ad5">
 
 " const pineconeIndex = await client.index("chatpdf"); " it have same name like in pinecone dashboard
 
 2. I connected the credit card to the open ai account 
 
 
<img width="1680" alt="Screenshot 2023-09-24 at 16 00 24" src="https://github.com/Elliott-Chong/chatpdf-yt/assets/101702271/a8796ac5-6a6e-436d-b149-59a595ff25f9">

but that didn't solve the problem, I get exactly the same error

**Comment by ybekocak** [comment]
Same here, is there anyone found a solution?

**Comment by amilali** [comment]
<img width="414" alt="image" src="https://github.com/Elliott-Chong/chatpdf-yt/assets/66510886/352685a9-2cc1-4c3f-b4fc-c0b01590df8b">

i am also getting same axios error is anybody solve this issue. @ybekocak @GheorgheMocanu @AymanBoumait @0xalphaprime @huynextlevel

**Comment by brygulley25** [comment]
Same I'm getting that same error , any resolutions ?

**Comment by johnsethsalazar** [comment]
Had the same issue.

![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/24352433/8a72d1b0-31ee-4bf5-bd2e-ba7b87acd77b)


It might be that you are out of credits. You can try to check result.data in the embeddings.ts file like this:

```
import {OpenAIApi, Configuration} from 'openai-edge'

const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(config);

export async function getEmbeddings(text: string) {
  try{
    const response = await openai.createEmbedding({
      model: "text-embedding-ada-002",
      input: text.replace(/\n/g, " "),
    });
    const result = await response.json();
    console.log('API response:', result); // Debug log
    console.log('Embeddings:', result.data[0].embedding); // Debug log
    return result.data[0].embedding as number[];
  }catch(error){
    console.log('error calling openai embeddings api', error);
    throw error;
  }
}
```

![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/24352433/1c1c6889-3177-49c0-bc22-ca0a1573c4b2)

**Comment by Sudipta013** [comment]
Hey guys i have found a simple solution for this..
While i was debugging this Axios error: internal server error 500 : 
IF you notice your concole in code editor there might be written file/module not found error. 
Solution:
When you are trying to upload a File....
1. Check if the file is successfully uploaded to S3. If yes, then your connection with S3 is all good and UploadtoS3() function has no issues.
2. Now, check  if you follow the code of route.ts. It calls the function loads3intoPinecone() which takes us to pinecone.ts.
3. Now in pinecone.ts under the method loads3intoPinecone(), the method downloadfrons3 is called which helps us to download our document from S3.
4. This takes us s3-server.ts file , here we are using fs module to write our downloaded file into a tmp file. 
fs.writeFileSync(file_name, obj.Body as Buffer)
**i suggest try cosole.log(file_name) tocheck if you are getting the file_name ** if not which was in my case you can follow the next step.
5. Now , As the file_name is not available since the module/file is not downloaded from s3 a server-side error is poping up and also module not found error. 
6.  Finally, To fix this issue, you can try creating the /tmp directory manually and setting the correct permissions to make it writable. For this-
7. Go to the folder of your Project
8. NOTE: This is for windows 
9. open the path in terminal and type the following command
10. mkdir /tmp
11. icacls C:\tmp /grant Everyone:F
