### ISSUE TITLE
Error 301 Redirect in AWS S3

### ISSUE THREAD

**Issue by kalilfagundes** [Elliott-Chong/chatpdf-yt#28]
**Error 1:**

- event compiled client and server successfully in 2.2s (2594 modules)
uploads/1699211543893CCMEI-49690000000150.pdf CCMEI-49690000000150.pdf
downloading s3 into file system
PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at throwDefaultError (C:\Users\kalil\chatpdf-yt\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)
    at C:\Users\kalil\chatpdf-yt\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
    at de_GetObjectCommandError (C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kalil\chatpdf-yt\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:14:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async eval (webpack-internal:///(rsc)/./src/lib/s3-server.ts:25:25) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 301,
    requestId: 'BN7JTW2P1NK235RP',
    extendedRequestId: 'P5G9UMk7/CcxGZeT+S8XL2Pd8/xhmBjpnEGXUkSF8P+wyRVqXkT74rcmUCnV6V477NSstvx8MXc=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'PermanentRedirect',
  Endpoint: 'pdfconversa-yt.s3-us-west-2.amazonaws.com',
  Bucket: 'pdfconversa-yt',
  RequestId: 'BN7JTW2P1NK235RP',
  HostId: 'P5G9UMk7/CcxGZeT+S8XL2Pd8/xhmBjpnEGXUkSF8P+wyRVqXkT74rcmUCnV6V477NSstvx8MXc='
}
PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at throwDefaultError (C:\Users\kalil\chatpdf-yt\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)
    at C:\Users\kalil\chatpdf-yt\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
    at de_GetObjectCommandError (C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kalil\chatpdf-yt\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:14:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20
    at async C:\Users\kalil\chatpdf-yt\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async eval (webpack-internal:///(rsc)/./src/lib/s3-server.ts:25:25) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 301,
    requestId: 'BN7JTW2P1NK235RP',
    extendedRequestId: 'P5G9UMk7/CcxGZeT+S8XL2Pd8/xhmBjpnEGXUkSF8P+wyRVqXkT74rcmUCnV6V477NSstvx8MXc=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'PermanentRedirect',
  Endpoint: 'pdfconversa-yt.s3-us-west-2.amazonaws.com',
  Bucket: 'pdfconversa-yt',
  RequestId: 'BN7JTW2P1NK235RP',
  HostId: 'P5G9UMk7/CcxGZeT+S8XL2Pd8/xhmBjpnEGXUkSF8P+wyRVqXkT74rcmUCnV6V477NSstvx8MXc='
}
- wait compiling...
- event compiled client and server successfully in 968 ms (2267 modules)

**In console:**
![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/92411438/7fdefac4-2e7b-4ea0-bb80-5b4d03f5d758)

I get the error and then I go to upload page again. 

**Error 2:**
Also getting some Hydratation errors, but it does not seem critical.

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <div> in <html>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Has anyone faced similar issues?

**Comment by kalilfagundes** [comment]
![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/92411438/152e82f5-2e5b-4b89-acbc-b965a8fc1281)

**Comment by kalilfagundes** [comment]
I had to change the Amazon server region in src/lib/.
Changed s3 file and s3-server file.
